"""Initial migration

Revision ID: 321e23d6fce0
Revises: 3f041c541435
Create Date: 2024-02-02 12:34:59.678204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321e23d6fce0'
down_revision = '3f041c541435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
